#!/usr/bin/env bash

# Check if all four arguments are provided
if [ $# -ne 4 ]; then
    echo "Usage: $0 file_path user_name server_ip ssh_key"
    exit 1
fi

# Assign the arguments to variables
file_path=$1
user_name=$2
server_ip=$3
ssh_key_file_path=$4

# Transfer the File using scp
scp -i "$ssh_key_file_path" "$file_path" "$user_name@$server_ip:~"

# Check the Exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "File transfer failed!"
fi
